# Generated by Django 3.2.13 on 2022-08-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('faculty', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
                ('phoneNumber', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], default='A', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentinfo.department')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
